/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factura;

/**
 *
 * @author Ivan
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CantP3 = new javax.swing.JTextField();
        NomP3 = new javax.swing.JTextField();
        ValP3 = new javax.swing.JTextField();
        TotP3 = new javax.swing.JTextField();
        TotP2 = new javax.swing.JTextField();
        ValP2 = new javax.swing.JTextField();
        NomP2 = new javax.swing.JTextField();
        CantP2 = new javax.swing.JTextField();
        TotP1 = new javax.swing.JTextField();
        ValP1 = new javax.swing.JTextField();
        NomP1 = new javax.swing.JTextField();
        CantP1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtSubTotal = new javax.swing.JTextField();
        TxtIVA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtDescuento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDescuento1 = new javax.swing.JLabel();
        cbP3 = new javax.swing.JComboBox<>();
        cbP1 = new javax.swing.JComboBox<>();
        cbP2 = new javax.swing.JComboBox<>();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cantidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, -1));

        jLabel3.setText("Valor unitario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 100, -1));

        jLabel4.setText("Importe");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 70, -1));

        CantP3.setText("4");
        jPanel1.add(CantP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, -1));

        NomP3.setText("Pan");
        NomP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomP3ActionPerformed(evt);
            }
        });
        jPanel1.add(NomP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, -1));

        ValP3.setText("500");
        jPanel1.add(ValP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 80, -1));
        jPanel1.add(TotP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 110, -1));
        jPanel1.add(TotP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 110, -1));

        ValP2.setText("2000");
        jPanel1.add(ValP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, -1));

        NomP2.setText("Leche");
        jPanel1.add(NomP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, -1));

        CantP2.setText("1");
        jPanel1.add(CantP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, -1));
        jPanel1.add(TotP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 110, -1));

        ValP1.setText("1500");
        jPanel1.add(ValP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, -1));

        NomP1.setText("Arroz");
        jPanel1.add(NomP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, -1));

        CantP1.setText("3");
        jPanel1.add(CantP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, -1));

        jLabel5.setText("Sub Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 210, 100, 20));

        jLabel6.setText("IVA 15%:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 100, 20));
        jPanel1.add(TxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, -1));

        TxtIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIVAActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, -1));

        jLabel7.setText("Descuento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 20));

        TxtDescuento.setText("0");
        jPanel1.add(TxtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Calcular factura en Java - NetBeans");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, -1));

        TxtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtTotal.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 110, 30));

        jLabel10.setText("Total a Pagar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 100, 30));

        jLabel11.setText("Valor descontado: $");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 100, 20));

        txtDescuento1.setText("-");
        jPanel1.add(txtDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 110, 20));

        cbP3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con Descuento", "Sin Descuento" }));
        jPanel1.add(cbP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        cbP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con Descuento", "Sin Descuento", " " }));
        cbP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP1ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        cbP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con descuento", "Sn descuento" }));
        cbP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP2ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // -------- PRODUCTO 1 --------
    int c1 = Integer.parseInt(CantP1.getText());
    double p1 = Double.parseDouble(ValP1.getText());
    String t1 = cbP1.getSelectedItem().toString();

    ProductoBase prod1 = t1.toLowerCase().contains("con")
            ? new ProductoDescuento(c1, p1)
            : new ProductoSinDescuento(c1, p1);

    double importe1 = prod1.calcularImporte();
    TotP1.setText("" + importe1);

    // -------- PRODUCTO 2 --------
    int c2 = Integer.parseInt(CantP2.getText());
    double p2 = Double.parseDouble(ValP2.getText());
    String t2 = cbP2.getSelectedItem().toString();

    ProductoBase prod2 = t2.toLowerCase().contains("con")
            ? new ProductoDescuento(c2, p2)
            : new ProductoSinDescuento(c2, p2);

    double importe2 = prod2.calcularImporte();
    TotP2.setText("" + importe2);

    // -------- PRODUCTO 3 --------
    int c3 = Integer.parseInt(CantP3.getText());
    double p3 = Double.parseDouble(ValP3.getText());
    String t3 = cbP3.getSelectedItem().toString();

    ProductoBase prod3 = t3.toLowerCase().contains("con")
            ? new ProductoDescuento(c3, p3)
            : new ProductoSinDescuento(c3, p3);

    double importe3 = prod3.calcularImporte();
    TotP3.setText("" + importe3);

    // -------- SUBTOTAL --------
    double subtotal = importe1 + importe2 + importe3;
    TxtSubTotal.setText("" + subtotal);

    // -------- IVA --------
    double iva = subtotal * 0.15;
    TxtIVA.setText("" + iva);

    // -------- TOTAL A PAGAR --------
    double total = subtotal + iva;
    TxtTotal.setText("" + total);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NomP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomP3ActionPerformed

    private void TxtIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIVAActionPerformed

    private void cbP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbP1ActionPerformed

    private void cbP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantP1;
    private javax.swing.JTextField CantP2;
    private javax.swing.JTextField CantP3;
    private javax.swing.JTextField NomP1;
    private javax.swing.JTextField NomP2;
    private javax.swing.JTextField NomP3;
    private javax.swing.JTextField TotP1;
    private javax.swing.JTextField TotP2;
    private javax.swing.JTextField TotP3;
    private javax.swing.JTextField TxtDescuento;
    private javax.swing.JTextField TxtIVA;
    private javax.swing.JTextField TxtSubTotal;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JTextField ValP1;
    private javax.swing.JTextField ValP2;
    private javax.swing.JTextField ValP3;
    private javax.swing.JComboBox<String> cbP1;
    private javax.swing.JComboBox<String> cbP2;
    private javax.swing.JComboBox<String> cbP3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDescuento1;
    // End of variables declaration//GEN-END:variables
}
